<Compile Include="frmThemLoai.cs">
  <SubType>Form</SubType>
</Compile>
<Compile Include="frmThemLoai.Designer.cs">
  <DependentUpon>frmThemLoai.cs</DependentUpon>
</Compile>
<Compile Include="frmHoaDon.cs">
  <SubType>Form</SubType>
</Compile>
<Compile Include="frmHoaDon.Designer.cs">
  <DependentUpon>frmHoaDon.cs</DependentUpon>
</Compile>
<Compile Include="frmMon.cs">
  <SubType>Form</SubType>
</Compile>
<Compile Include="frmMon.Designer.cs">
  <DependentUpon>frmMon.cs</DependentUpon>
</Compile>
<Compile Include="frmThemMon.cs">
  <SubType>Form</SubType>
</Compile>
<Compile Include="frmThemMon.Designer.cs">
  <DependentUpon>frmThemMon.cs</DependentUpon>
</Compile>

<!-- Helpers, Models, Program, Properties -->
<Compile Include="Helpers\ButtonHelper.cs" />
<Compile Include="Helpers\DataGridViewHelper.cs" />
<Compile Include="Helpers\LoaiMonHelper.cs" />
<Compile Include="Helpers\MonCard.cs">
  <SubType>Component</SubType>
</Compile>
<Compile Include="Models\ChiTietHoaDon.cs" />
<Compile Include="Models\HoaDon.cs" />
<Compile Include="DAL\HoaDonQueries.cs" />
<Compile Include="Models\Mon.cs" />
<Compile Include="DAL\MonQueries.cs" />
<Compile Include="MonDAO.cs" />
<Compile Include="MonInfo.cs" />
<Compile Include="Program.cs" />
<Compile Include="Properties\AssemblyInfo.cs" />
<Compile Include="Resource1.Designer.cs">
  <AutoGen>True</AutoGen>
  <DesignTime>True</DesignTime>
  <DependentUpon>Resource1.resx</DependentUpon>
</Compile>
<Compile Include="Resources.Designer.cs">
  <AutoGen>True</AutoGen>
  <DesignTime>True</DesignTime>
  <DependentUpon>Resources.resx</DependentUpon>
</Compile>
<Compile Include="Settings.Designer.cs">
  <AutoGen>True</AutoGen>
  <DesignTimeSharedInput>True</DesignTimeSharedInput>
  <DependentUpon>Settings.settings</DependentUpon>
</Compile>
<Compile Include="TaiKhoan.cs" />

<!-- EmbeddedResource -->
<EmbeddedResource Include="frmThemLoai.resx">
  <DependentUpon>frmThemLoai.cs</DependentUpon>
</EmbeddedResource>
<EmbeddedResource Include="frmHoaDon.resx">
  <DependentUpon>frmHoaDon.cs</DependentUpon>
</EmbeddedResource>
<EmbeddedResource Include="frmMon.resx">
  <DependentUpon>frmMon.cs</DependentUpon>
</EmbeddedResource>
<EmbeddedResource Include="frmThemMon.resx">
  <DependentUpon>frmThemMon.cs</DependentUpon>
</EmbeddedResource>
<EmbeddedResource Include="Properties\Resources.resx">
  <Generator>ResXFileCodeGenerator</Generator>
  <SubType>Designer</SubType>
</EmbeddedResource>
